server:
  port: 10001

spring:
  application:
    name: ffmpeg-m3u8-convertor

  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB

#m3u8视频转换配置
m3u8:
  transfer:
    base-path: D:/temp/video/base/
    temp-path: D:/temp/video/tmp/
    delete-temp-file: true
